# Generated by Django 3.2 on 2021-06-10 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LegalDoc',
            fields=[
                ('doc_id', models.AutoField(primary_key=True, serialize=False)),
                ('document_title', models.CharField(max_length=100, verbose_name='Breifly mention the title for the doc: ')),
                ('document_doc_url', models.FileField(upload_to='legal_docs', verbose_name='Upload the supporting document')),
                ('upload_date', models.DateField(auto_now=True, verbose_name='Date of upload ')),
            ],
        ),
    ]
